<hr/>

# Data Mining  [EN.550.636.02]

02/09/2018

**TA** - Cong Mu (cmu2@jhu.edu)   <br/>
**Office Hour** - Monday 9:00am ~ 11:00am

- **Python:** SciPy
- **Model:** Linear Regression, Linear Mixed-Effect Model
- **Q & A**

<hr/>


[Install Python](https://www.python.org/) <br/>
[Install Anaconda](https://www.continuum.io/downloads)

In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


<h2><font color="darkblue">Python</font></h2>
<hr/>

### SciPy
[Tutorial](https://docs.scipy.org/doc/scipy/reference/tutorial/index.html)

#### Linear Algebra

In [2]:
from scipy import linalg

- **scipy.linalg** vs **numpy.linalg**

 - numpy.linalg $ \subset $ scipy.linalg
 - scipy.linalg is faster ([BLAS](https://en.wikipedia.org/wiki/Basic_Linear_Algebra_Subprograms))

- **Inverse**

> Syntax:
- scipy.linalg.inv(a, overwrite_a=False, check_finite=True)

> Parameters:	
- **a** : array_like <br/> Square matrix to be inverted.
- **overwrite_a** : bool, optional <br/> Discard data in a (may improve performance). Default is False.
- **check_finite** : bool, optional <br/> Whether to check that the input matrix contains only finite numbers. Disabling may give a performance gain, but may result in problems (crashes, non-termination) if the inputs do contain infinities or NaNs.

> Returns:	
- **ainv** : ndarray <br/> Inverse of the matrix a.

In [3]:
A = np.array([[1,3,5],[2,5,1],[2,3,8]])
print('Original Matrix: \n', A)
A_inv = linalg.inv(A)
print('Inverse: \n', A_inv)
print('Check: \n', A.dot(linalg.inv(A)))

Original Matrix: 
 [[1 3 5]
 [2 5 1]
 [2 3 8]]
Inverse: 
 [[-1.48  0.36  0.88]
 [ 0.56  0.08 -0.36]
 [ 0.16 -0.12  0.04]]
Check: 
 [[  1.00000000e+00  -1.11022302e-16  -5.55111512e-17]
 [  3.05311332e-16   1.00000000e+00   1.87350135e-16]
 [  2.22044605e-16  -1.11022302e-16   1.00000000e+00]]


- **Determinant**

> Syntax:
- scipy.linalg.det(a, overwrite_a=False, check_finite=True)

> Parameters:	
- **a** : (M, M) array_like <br/> Square matrix.
- **overwrite_a** : bool, optional <br/> Allow overwriting data in a (may enhance performance).
- **check_finite** : bool, optional <br/> Whether to check that the input matrix contains only finite numbers. Disabling may give a performance gain, but may result in problems (crashes, non-termination) if the inputs do contain infinities or NaNs.

> Returns:	
- **det** : float or complex  <br/> Determinant of a.

In [4]:
A = np.array([[1,2],[3,4]])
print('Original Matrix: \n', A)
print('Determinant: ', linalg.det(A))

Original Matrix: 
 [[1 2]
 [3 4]]
Determinant:  -2.0


- **Decompositions**

> Syntax:
- scipy.linalg.eig(a, b=None, left=False, right=True, overwrite_a=False, overwrite_b=False, check_finite=True, homogeneous_eigvals=False)

> Parameters:	
- **a** : (M, M) array_like <br/> A complex or real matrix whose eigenvalues and eigenvectors will be computed.

> Returns:	
- **w** : (M,) or (2, M) double or complex ndarray  <br/> The eigenvalues, each repeated according to its multiplicity.
- **vr** : (M, M) double or complex ndarray  <br/> The normalized right eigenvector

In [5]:
A = np.array([[1, 2], [3, 4]])
print('Original Matrix: \n', A)
eigenvalues, eigenvector = linalg.eig(A)
print('Eigenvalues: ', eigenvalues)
print('Eigenvector: \n', eigenvector)

Original Matrix: 
 [[1 2]
 [3 4]]
Eigenvalues:  [-0.37228132+0.j  5.37228132+0.j]
Eigenvector: 
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


#### Statistics

In [6]:
from scipy import stats

- **Random Variables**

> The main public methods for continuous RVs are:
- rvs: Random Variates
- pdf: Probability Density Function
- cdf: Cumulative Distribution Function
- sf: Survival Function (1-CDF)
- ppf: Percent Point Function (Inverse of CDF)
- isf: Inverse Survival Function (Inverse of SF)
- stats: Return mean, variance, (Fisher’s) skew, or (Fisher’s) kurtosis
- moment: non-central moments of the distribution

In [7]:
from scipy.stats import norm

In [8]:
norm.rvs(loc=0, scale=1, size=5, random_state=2018)  # scale is standard deviation  

array([-0.2767676 ,  0.581851  ,  2.14839926, -1.279487  ,  0.50227689])

In [9]:
norm.rvs(loc=0, scale=1, size=5, random_state=2018)

array([-0.2767676 ,  0.581851  ,  2.14839926, -1.279487  ,  0.50227689])

In [11]:
norm.rvs(loc=0, scale=1, size=(9,2), random_state=2018)

array([[-0.2767676 ,  0.581851  ],
       [ 2.14839926, -1.279487  ],
       [ 0.50227689,  0.8560293 ],
       [-0.14279008,  0.11007867],
       [-0.68806479,  0.43356408],
       [ 0.510221  , -0.16513097],
       [-1.35177905,  0.54663075],
       [ 1.23065512,  1.0764461 ],
       [-1.21062488, -0.30667657]])

In [12]:
norm.pdf([0, 2], loc=0, scale=1)

array([ 0.39894228,  0.05399097])

In [13]:
norm.cdf([0, 1], loc=0, scale=1)

array([ 0.5       ,  0.84134475])

<h2><font color="darkblue">Model</font></h2>
<hr/>

### Linear Regression
[Tutorial](http://scikit-learn.org/stable/modules/linear_model.html)

> $\displaystyle Y = X \beta + \epsilon $
>
> $\displaystyle \hat\beta = (X^T X)^{-1} X^T Y = X^+ Y$

In [14]:
from sklearn.preprocessing import PolynomialFeatures as poly

[PolynomialFeatures](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PolynomialFeatures.html)

In [15]:
Y = np.arange(10)
Y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
X = np.arange(20).reshape(10, 2)
X

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [17]:
poly2 = poly(2)
X2 = poly2.fit_transform(X)
X2

array([[   1.,    0.,    1.,    0.,    0.,    1.],
       [   1.,    2.,    3.,    4.,    6.,    9.],
       [   1.,    4.,    5.,   16.,   20.,   25.],
       [   1.,    6.,    7.,   36.,   42.,   49.],
       [   1.,    8.,    9.,   64.,   72.,   81.],
       [   1.,   10.,   11.,  100.,  110.,  121.],
       [   1.,   12.,   13.,  144.,  156.,  169.],
       [   1.,   14.,   15.,  196.,  210.,  225.],
       [   1.,   16.,   17.,  256.,  272.,  289.],
       [   1.,   18.,   19.,  324.,  342.,  361.]])

In [18]:
poly2 = poly(2, interaction_only=True)
X2 = poly2.fit_transform(X)
X2

array([[   1.,    0.,    1.,    0.],
       [   1.,    2.,    3.,    6.],
       [   1.,    4.,    5.,   20.],
       [   1.,    6.,    7.,   42.],
       [   1.,    8.,    9.,   72.],
       [   1.,   10.,   11.,  110.],
       [   1.,   12.,   13.,  156.],
       [   1.,   14.,   15.,  210.],
       [   1.,   16.,   17.,  272.],
       [   1.,   18.,   19.,  342.]])

In [19]:
from sklearn.model_selection import train_test_split

[train_test_split](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html)

In [20]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=2018)
print('X_train: \n', X_train)
print('X_test: \n', X_test)
print('Y_train: \n', Y_train)
print('Y_test: \n', Y_test)

X_train: 
 [[16 17]
 [18 19]
 [ 8  9]
 [10 11]
 [ 2  3]
 [ 4  5]
 [12 13]]
X_test: 
 [[ 0  1]
 [ 6  7]
 [14 15]]
Y_train: 
 [8 9 4 5 1 2 6]
Y_test: 
 [0 3 7]


In [21]:
from sklearn import linear_model

[LinearRegression](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html)

In [22]:
lm = linear_model.LinearRegression()
lm.fit(X_train, Y_train);

In [23]:
lm.coef_

array([ 0.25,  0.25])

In [24]:
lm.intercept_

-0.25000000000000178

In [25]:
lm.predict(X_test)

array([ -1.66533454e-15,   3.00000000e+00,   7.00000000e+00])

In [26]:
lm.score(X_test, Y_test)  # R^2 must fit first

1.0

### Linear Mixed-Effect Model
[Tutorial](http://www.statsmodels.org/dev/mixed_linear.html)

In [27]:
import pandas as pd

- **Longitudinal Data**

In [28]:
df = pd.DataFrame({'id': [1,1,1,2,2,3,3,3,3], 
                   'week': [0,1,2,0,1,0,1,2,3], 
                   'y': np.random.randint(1,20,9),
                   'x1': np.random.randn(9),
                   'x2': np.random.randn(9)})
df

id  week        x1        x2   y
0   1     0  1.921812 -0.973643   5
1   1     1 -0.528911  0.419067  19
2   1     2 -1.131307  0.205320  19
3   2     0  1.070019  1.045759  10
4   2     1 -1.109098 -0.324795   7
5   3     0  0.974150 -0.488276   6
6   3     1  1.026907  0.171584   8
7   3     2 -0.504214  0.555015  12
8   3     3 -0.389387  2.985775   5

- **Linear Model**
> $\displaystyle y = \beta_0 + \beta_1 x_1 + \epsilon $
>

- **Linear Mixed-Effect Model**
> $\displaystyle y_{ij} = \beta_{0i} + \beta_{1i} x_{1ij} + \epsilon_{ij} $
>
> $\displaystyle \beta_{0i} = \gamma_0 + \gamma_{0i} $, $\quad \displaystyle \beta_{1i} = \gamma_1 + \gamma_{1i} $
>
> $\displaystyle y_{ij} = \gamma_0 + \gamma_{0i} + (\gamma_1 + \gamma_{1i}) x_{1ij} + \epsilon_{ij} = (\gamma_0 + \gamma_1 x_{1ij}) + (\gamma_{0i} + \gamma_{1i} x_{1ij} + \epsilon_{ij}) $

In [30]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [31]:
data = sm.datasets.get_rdataset("dietox", "geepack").data
data.head(20)

Weight        Feed  Time   Pig  Evit  Cu  Litter
0   26.50000         NaN     1  4601     1   1       1
1   27.59999    5.200005     2  4601     1   1       1
2   36.50000   17.600000     3  4601     1   1       1
3   40.29999   28.500000     4  4601     1   1       1
4   49.09998   45.200001     5  4601     1   1       1
5   55.39999   56.900002     6  4601     1   1       1
6   59.59998   71.700005     7  4601     1   1       1
7   67.00000   86.800001     8  4601     1   1       1
8   76.59998  104.900002     9  4601     1   1       1
9   86.50000  123.000000    10  4601     1   1       1
10  91.59998  140.900002    11  4601     1   1       1
11  98.59998  160.000000    12  4601     1   1       1
12  27.00000         NaN     1  4643     1   1       2
13  31.79999    6.400002     2  4643     1   1       2
14  39.00000   21.500000     3  4643     1   1       2
15  44.79999   33.900002     4  4643     1   1       2
16  50.89999   44.900002     5  4643     1   1       2
17  57.39999   58.800000     6  4643     1   1       2
18  62.50000   73.700001     7  4643     1   1       2
19  71.69995   92.800003     8  4643     1   1       2

In [32]:
md = smf.mixedlm('Weight ~ Time', data, groups=data['Pig']) # re_formula='~ Time'
mdf = md.fit()
print(mdf.summary())

         Mixed Linear Model Regression Results
Model:            MixedLM Dependent Variable: Weight    
No. Observations: 861     Method:             REML      
No. Groups:       72      Scale:              11.3669   
Min. group size:  11      Likelihood:         -2404.7753
Max. group size:  12      Converged:          Yes       
Mean group size:  12.0                                  
--------------------------------------------------------
             Coef.  Std.Err.    z    P>|z| [0.025 0.975]
--------------------------------------------------------
Intercept    15.724    0.788  19.952 0.000 14.179 17.268
Time          6.943    0.033 207.939 0.000  6.877  7.008
groups RE    40.394    2.149                            



> $\displaystyle Weight_{ij} = (\gamma_0 + \gamma_1 Time_{ij}) + (\gamma_{0i} + \epsilon_{ij}) $

In [33]:
mdf.params

Intercept    15.723523
Time          6.942505
groups RE     3.553634
dtype: float64

In [34]:
mdf.random_effects

{4601: groups   -1.213037
 dtype: float64, 4602: groups    3.086142
 dtype: float64, 4603: groups    3.981795
 dtype: float64, 4605: groups    6.790923
 dtype: float64, 4641: groups    9.152234
 dtype: float64, 4643: groups    0.887694
 dtype: float64, 4645: groups    4.421497
 dtype: float64, 4756: groups   -11.456167
 dtype: float64, 4757: groups    0.830694
 dtype: float64, 4759: groups   -3.085792
 dtype: float64, 4760: groups   -19.810266
 dtype: float64, 4813: groups    2.49989
 dtype: float64, 4814: groups   -0.366236
 dtype: float64, 4815: groups   -0.700069
 dtype: float64, 4817: groups    2.361469
 dtype: float64, 4854: groups   -1.188612
 dtype: float64, 4856: groups    6.432667
 dtype: float64, 4857: groups    1.929924
 dtype: float64, 4858: groups    2.337039
 dtype: float64, 5389: groups   -4.714274
 dtype: float64, 5392: groups   -10.796642
 dtype: float64, 5497: groups   -4.640988
 dtype: float64, 5500: groups   -14.004736
 dtype: float64, 5501: groups    6.074404
 dtyp